# Generated by Django 5.1.7 on 2025-04-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=160, verbose_name="Категории"),
        ),
    ]
