# Generated by Django 5.1.7 on 2025-04-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterField(
            model_name="actor",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="actors/", verbose_name="Изображение"
            ),
        ),
    ]
